version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: datacose_db
      POSTGRES_USER: datacose_user
      POSTGRES_PASSWORD: datacose_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
